### ISSUE TITLE
Unwanted exception occurs in PluginCaller.java

### ISSUE THREAD

**Issue by Sakib37** [openbaton/openbaton-libs#8]
In PluginCaller.java class always a nullpointer  exception raised in [this](https://github.com/openbaton/openbaton-libs/blob/master/plugin/src/main/java/org/openbaton/plugin/utils/PluginCaller.java#L133) line.

I think this exception should not be raised all the time. 
![screenshot from 2016-12-21 19-39-18](https://cloud.githubusercontent.com/assets/10330594/21402940/213612a8-c7bb-11e6-9d1a-ecf2d33c4ab9.png)

**Comment by marcellom** [comment]
I don't see the exactly the problem, the line you refer is empty in the real code. The line, highlighted in blue, in your pic, is a simple set and cannot launch an exception. Could you be more precise please?
The only problem I see it that Gson (at line 138 in your pic) could throw a NullPointerException when it tries to transform pluginMessage into a Json, because the property interfaceClass is never set and in the toString there is interfaceClass.getSimpleName().

**Comment by Sakib37** [comment]
I think there is some change pushed in the code recently which changed my line number link. However, the problem is after line number 135 in the picture it always gives a null pointer exception. I do not understand after creating an object why always there is an exception raised? To be more specific I am talking about the following line-
`PluginMessage pluginMessage = new PluginMessage();`

**Comment by marcellom** [comment]
Ok, Have you tried with the newest version? And how do you execute such code? This project is only a set of libraries used by other Open Baton projects.

**Comment by Sakib37** [comment]
I faced this while developing a VNFM that use this library. 

Well I did not tried the new version. Not sure its fixed or not. As it does not affect that much I did not pay attention later. But I thought it would be better to inform the developers.

**Comment by lorenzotomasini** [comment]
@Sakib37 Could you send also the stack trace?

**Comment by Sakib37** [comment]
@lorenzotomasini  -  Unfortunately I do not have the stack trace. 
I faced this issue long before and cannot remember why I faced this. As far I can remember this issue did not affect my VNFM development by any means. 

I opened this issue to inform developers, in case this means something different to them.  Its okay for me if the issue is closed.
