### ISSUE TITLE
Using multiple JSON serialisers is confusing

### ISSUE THREAD

**Issue by mcilloni** [openbaton/openbaton-libs#9]
[vnfm-sdk-rest](https://github.com/openbaton/openbaton-libs/tree/master/vnfm-sdk-rest) uses Jackson, while the rest of the project uses Gson to serialise/deserialise JSON.

This can lead to an inconsistent and confusing serialisation behaviour, like in [VirtualNetworkFunctionRecord](https://github.com/openbaton/openbaton-libs/blob/master/catalogue/src/main/java/org/openbaton/catalogue/mano/descriptor/VirtualNetworkFunctionDescriptor.java#L96), where the `endpoint` field is marked `@JsonIgnore` using a Jackson tag, but it's still considered (correctly) when using Gson.

I would consider dropping Jackson to reduce these ambiguities and make the way the project handles JSON more consistent.

**Comment by marcellom** [comment]
I checked and I agree with the issue. I'll fix it in a specific branch and then I'll refer this issue with the relative pull request.

**Comment by marcellom** [comment]
This b2a6ccbe4d0ddf64e94c8b09595b2362eb0bbf22 should fix this issue. I will test tomorrow and make a pull request.
